spring:
#  datasource:
#    jobconfig:
#      driverClassName:
#      jdbc-url:
#      username:
#      password:
#      maximum-pool-size: 5
#      minimum-pool-size: 2
#    inputprocessor:
#      driverClassName:
#      jdbc-url:
#      username:
#      password:
#      maximum-pool-size: 5
#      minimum-pool-size: 2
#    outputprocessor:
#      driverClassName:
#      jdbc-url:
#      username:
#      password:
#      maximum-pool-size: 5
#      minimum-pool-size: 2
#    businessprocessor:
#      driverClassName:
#      jdbc-url:
#      username:
#      password:
#      maximum-pool-size: 5
#      minimum-pool-size: 2
  mail:
    username:
    password:
    host: smtp.163.com
    properties:
      mail:
        smtp:
          ssl:
            enable: false
            required: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
sql:
  job_config:
    parent: SELECT * from MONITOR_TRACKER_JOB_CONFIG
    detail: SELECT * FROM MONITOR_TRACKER_JOB_DETAIL_CONFIG

  inputprocessor:
    number_upper_limit_breach: SELECT * FROM TEST

  outputprocessor:
    number_upper_limit_breach:
      get_last_result: SELECT * FROM NUMBER_UPPER_LIMIT_BREACH WHERE ACTIVE = 'A'
      inactive_old_result: UPDATE NUMBER_UPPER_LIMIT_BREACH SET ACTIVE = 'I' WHERE ACTIVE = 'A'
      insert_new_result: "INSERT INTO NUMBER_UPPER_LIMIT_BREACH(SCHEMA_NAME, TABLE_NAME, COLUMN_NAME, CURRENT_VALUE, LIMIT_VALUE,
                          BURN_RATE, DAYS_REACH_80, STATUS, CREATE_TIME) VALUES(:schemaName, :tableName, :columnName, :currentValue,
                          :limitValue, :burnRate, :daysReach80%, :active, sysdate)"