spring:
  datasource:
    jobconfig:
      driverClassName: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/fly?serverTimezone=UTC
      username: root
      password: *
      maximumPoolSize: 5
      minimumIdle: 2
    inputprocessor:
      driverClassName: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/fly?serverTimezone=UTC
      username: root
      password: *
      maximumPoolSize: 5
      minimumIdle: 2
    outputprocessor:
      driverClassName: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/fly?serverTimezone=UTC
      username: root
      password: *
      maximumPoolSize: 15
      minimumIdle: 10
    businessprocessor:
      driverClassName: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/fly?serverTimezone=UTC
      username: root
      password: *
      maximumPoolSize: 15
      minimumIdle: 10
  mail:
    username:
    password:
    host: smtp.163.com
    properties:
      mail:
        smtp:
          ssl:
            enable: false
            required: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
global:
  env: SIT
sql:
  job_config:
    parent: SELECT * from MONITOR_TRACKER_JOB_CONFIG
    detail: SELECT * FROM MONITOR_TRACKER_JOB_DETAIL_CONFIG WHERE JOB_ID = ?

  inputprocessor:
    number_upper_limit_breach: SELECT * FROM TEST

  outputprocessor:
    number_upper_limit_breach:
      get_last_result: SELECT * FROM NUMBER_UPPER_LIMIT_BREACH WHERE ACTIVE = 'A' AND SCHEMA_NAME = ?
      inactive_old_result: UPDATE NUMBER_UPPER_LIMIT_BREACH SET ACTIVE = 'I' WHERE ACTIVE = 'A' and SCHEMA_NAME = ?
      insert_new_result: "INSERT INTO NUMBER_UPPER_LIMIT_BREACH(SCHEMA_NAME, TABLE_NAME, COLUMN_NAME, COLUMN_DATA_TYPE, CURRENT_VALUE, LIMIT_VALUE,
                          BURN_RATE, DAYS_REACH_80_PERCENT, STATUS, CREATE_TIME) VALUES(?, ?, ?, ?, ?, ?, ?, ?, 'A', sysdate)"